### ISSUE TITLE
mistype.co is unavailable

### ISSUE THREAD

**Issue by veelenga** [marinintim/mistype#17]
Hey @marinintim. Mistype is a very cool and useful tool. I have been using it for my blog, but few weeks ago it stopped working. What happened ? Any plans to fix it ?

**Comment by marinintim** [comment]
@veelenga Sorry, domain had expired and I forgot to renew it -- but I plan to bring it back in new year (along with new backend and lots of features)

**Comment by veelenga** [comment]
Glad to hear! Will wait for renewal and new features. Happy holidays :santa:

**Comment by veelenga** [comment]
Hey again. What's the status here ? Is it going to be maintained ?

**Comment by marinintim** [comment]
@veelenga: sorry, life is life!

If all would going according to plans then in a two weeks I'll have a new version deployed (though on another domain).
